stages:
    - build
    - test

build:
    image: node:24.7.0-alpine
    stage: build
    script:
        - node --version
        - npm --version
        - npm ci
        - npm run build
    artifacts:
        paths:
            - build/

test_artifacts:
    image: alpine
    stage: test
    script:
        - test -f build/index.html

test_service_healthy:
    image: node:24.7.0-alpine
    stage: test
    script:
        - apk add curl
        - npm install -g serve
        - serve -s build &
        - sleep 10
        - curl -I localhost:3000

test_unit:
    image: node:24.7.0-alpine
    stage: test
    script:
        - npm ci
        - npm test
    artifacts:
        when: always
        paths:
            - reports/html/junit.xml
        reports:
            junit: junit.xml