workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

variables:
  NETLIFY_SITE_ID: "d95f54c1-7c0f-46d5-9797-6a795a16f84b"

stages:
  - build
  - test
  - deploy_review
  - deploy_staging
  - deploy_prod

build_website:
  image: node:22-alpine
  stage: build
  script:
    - node --version
    - npm --version
    - npm ci
    - npm run build
  artifacts:
    paths:
      - build/

test_artifact:
  image: alpine
  stage: test
  script:
    - test -f build/index.html

unit_tests:
  image: node:22-alpine
  stage: test
  script:
    - npm ci
    - npm test
  artifacts:
    when: always
    reports:
      junit: reports/junit.xml

netlify_review:
  image: node:22-alpine
  stage: deploy_review
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH
  environment:
    name: preview/$CI_COMMIT_REF_SLUG
    url: $REVIEW_URL
  before_script:
    - npm install -g netlify-cli
    - apk add curl jq
  script:
    - netlify --version
    - netlify status
    - echo "Deploying to site id $NETLIFY_SITE_ID"
    - netlify deploy --dir build --no-build --json | tee deploy-result.json
    - REVIEW_URL=$(jq -r '.deploy_url' deploy-result.json)
    - echo $REVIEW_URL
    - curl $REVIEW_URL | grep 'GitLab'
    - echo "REVIEW_URL=$REVIEW_URL" > deploy.env
    - cat deploy.env
  artifacts:
    reports:
      dotenv: deploy.env

netlify_staging:
  image: node:22-alpine
  stage: deploy_staging
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  environment:
    name: staging
    url: "https://staging--site-gitlab-cicd.netlify.app/"
  before_script:
    - npm install -g netlify-cli
    - apk add curl
  script:
    - netlify --version
    - netlify status
    - echo "Deploying to site id $NETLIFY_SITE_ID"
    - netlify deploy --alias staging --dir build --no-build
    - curl $CI_ENVIRONMENT_URL | grep 'GitLab'

netlify_prod:
  image: node:22-alpine
  stage: deploy_prod
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  environment: production
  before_script:
    - npm install -g netlify-cli
    - apk add curl
  script:
    - netlify --version
    - netlify status
    - echo "Deploying to site id $NETLIFY_SITE_ID"
    - netlify deploy --prod --dir build --no-build
    - curl $CI_ENVIRONMENT_URL | grep 'GitLab'
