variables:
  NETLIFY_SITE_ID: 'd95f54c1-7c0f-46d5-9797-6a795a16f84b'

stages:
  - build
  - test
  - deploy_staging
  - deploy_prod

build_website:
  image: node:22-alpine
  stage: build
  script:
    - node --version
    - npm --version
    - npm ci
    - npm run build
  artifacts:
    paths: 
      - build/

test_artifact:
  image: alpine
  stage: test
  script:
    - test -f build/index.html

unit_tests:
  image: node:22-alpine
  stage: test
  script:
    - npm ci
    - npm test
  artifacts:
    when: always
    reports:
      junit: reports/junit.xml

netlify_staging:
  image: node:22-alpine
  stage: deploy_staging
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  before_script: 
    - npm install -g netlify-cli
    - apk add curl
  script:
    - netlify --version
    - netlify status
    - echo "Deploying to site id $NETLIFY_SITE_ID"
    - netlify deploy --alias=staging --dir=build
    - curl 'https://staging--site-gitlab-cicd.netlify.app/' | grep 'GitLab'

netlify_prod:
  image: node:22-alpine
  stage: deploy_prod
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  before_script: 
    - npm install -g netlify-cli
    - apk add curl
  script:
    - netlify --version
    - netlify status
    - echo "Deploying to site id $NETLIFY_SITE_ID"
    - netlify deploy --prod --dir=build
    - curl 'https://site-gitlab-cicd.netlify.app/' | grep 'GitLab'
  