stages:
    - build
    - setup
    - test

build:
    image: node:24.7.0-alpine
    stage: build
    script:
        - node --version
        - npm --version
        - npm ci
        - npm run build
    artifacts:
        paths:
            - build/

setup:
    image: node:24.7.0-alpine
    stage: setup
    script:
        - apk add curl
        - npm install -g serve
        - serve -s build &
        - test -f build/index.html
        - sleep 10
        - curl -I localhost:3000

test:
    image: node:24.7.0-alpine
    stage: test
    script:
        - npm ci
        - npm test
    artifacts:
    when: always
    paths:
      - reports/html/junit.xml
    reports:
      junit: reports/html/junit.xml