workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

variables:
  VITE_APP_VERSION: $CI_COMMIT_SHORT_SHA
  NETLIFY_IMAGE_VERSION: latest
  NETLIFY_DOCKER_IMAGE: '$CI_REGISTRY_IMAGE/netlify:$NETLIFY_IMAGE_VERSION'

stages:
  - build
  - test
  - deploy_review
  - post_deploy_review
  - deploy_staging
  - deploy_prod

build_website:
  image: node:22-alpine
  stage: build
  script:
    - node --version
    - npm --version
    - npm ci
    - npm run build
  artifacts:
    paths:
      - build/

test_artifact:
  image: alpine
  stage: test
  script:
    - test -f build/index.html

unit_tests:
  image: node:22-alpine
  stage: test
  script:
    - npm ci
    - npm test
  artifacts:
    when: always
    reports:
      junit: reports/junit.xml

netlify_review:
  image: $NETLIFY_DOCKER_IMAGE
  stage: deploy_review
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH
  environment:
    name: preview/$CI_COMMIT_REF_SLUG
    url: $REVIEW_URL
  script:
    - netlify --version
    - netlify status
    - echo "Deploying to site id $NETLIFY_SITE_ID"
    - netlify deploy --dir build --no-build --json | tee deploy-result.json
    - REVIEW_URL=$(jq -r '.deploy_url' deploy-result.json)
    - echo $REVIEW_URL
    - curl $REVIEW_URL | grep 'GitLab'
    - echo "REVIEW_URL=$REVIEW_URL" > deploy.env
    - cat deploy.env
  artifacts:
    reports:
      dotenv: deploy.env

post_deploy_review:
  image: mcr.microsoft.com/playwright:v1.49.1-noble
  stage: post_deploy_review
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH
  variables:
    APP_BASE_URL: $REVIEW_URL
  script:
    - echo $REVIEW_URL
    - echo $APP_BASE_URL
    - npm ci
    - npm run e2e
  artifacts:
    when: always
    paths:
      - reports/
    reports:
      junit: reports/playwright-junit.xml

netlify_staging:
  image: $NETLIFY_DOCKER_IMAGE
  stage: deploy_staging
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  environment: staging
  script:
    - netlify --version
    - netlify status
    - echo "Deploying to site id $NETLIFY_SITE_ID"
    - netlify deploy --alias staging --dir build --no-build
    - curl $CI_ENVIRONMENT_URL | grep 'GitLab'

netlify_prod:
  image: $NETLIFY_DOCKER_IMAGE
  stage: deploy_prod
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  environment: production
  script:
    - netlify --version
    - netlify status
    - echo "Deploying to site id $NETLIFY_SITE_ID"
    - netlify deploy --prod --dir build --no-build
    - curl $CI_ENVIRONMENT_URL | grep 'GitLab'
