stages:
    - build

build:
    image: node:24.7.0-alpine
    stage: build
    script:
        - node --version
        - npm --version
        - npm ci
        - npm run build
    artifacts:
        paths:
            - build/